### ISSUE TITLE
getAvatar not returning photoUrl

### ISSUE THREAD

**Issue by XBlack97** [alexstyl/facebook-compose#2]
The funtion `val avatar = "${requireNotNull(currentUser.photoUrl)}access_token=$accessToken"` doesn't return the currentUser PhotoUrl. I logged it to figure what it is printing and it's quite confusing

**Output**
`https://graph.facebook.com/2320946994746820/pictureaccess_token=EAAJraXYVZCSsBAJ9aOCVyjIz2fZCEZCUXnklNoLI6AIVI6RdYJbmmT8L7pJuEfYCeS4773L11SeAXBv2ZCaOJZCEYZBqtYjZCiGu8XTj9xzffqF4HrQbgnCVS5ZAMXZCdT2fLu3p7ZC4SMg9DjGCVc2rLH0FlqkRcS5geFQOod7o1z0gKTLZBEZCxExuZACnwgpzaKajMvF7kNoqZA2jmu0SlUjDyDTAotsr3Goji782BbwJwD0pOs6vLg1rT4`

i looked it up and this webpage displays 
<img width="1192" alt="Screenshot 2022-12-05 at 3 42 34 PM" src="https://user-images.githubusercontent.com/32486661/205665611-c99fa2a7-826c-40d2-ae1e-e137d14b3bb5.png">

**Comment by alexstyl** [comment]
Hi @XBlack97. It seems like you are missing a `?` right after the `picture` part of the url. 

It should be `https://graph.facebook.com/2320946994746820/picture?access_token...`, [like you see here](https://github.com/alexstyl/facebook-compose/blob/d0a8cfcf2b68b02c8389dd0f70f95b9522578e28/app/src/main/java/co/composables/fbcompose/HomeScreenViewModel.kt#L84).

Let me know if that sorts out the issue

**Comment by XBlack97** [comment]
Oh boy, can't believe how that get past me, thanks for the help...very much appreciated
